# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'alan_bishaev_HW5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for alan_bishaev_HW5
  pod 'MyButton3', :path => '../Libs/MyButton3'
end
